[package]
name = "lattirust-arithmetic"
version = "0.0.1-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = "0.4.2"
ark-serialize = "0.4.2"
ark-std = "0.4.0"
bincode = "1.3.3"
bitter = "0.6.2"
delegate = "0.12.0"
delegate-attr = "0.3.0"
derive_more = "0.99.17"
nalgebra = { version = "0.32.5", features = ["serde-serialize", "rayon"] }
nalgebra-sparse = "0.9.0"
nimue = { version = "0.0.1", git = "https://github.com/cknabs/nimue", branch = "absorb_unchecked-non-recursive" }
num-traits = "0.2.18"
rayon = "1.10.0"
rounded-div = "0.1.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_with = "3.7.0"
zeroize = "1.7.0"
num-bigint = "0.4.4"
